return {
   "nvim-treesitter/nvim-treesitter",
   build = ":TSUpdate",
   event = {
      "BufReadPost",
      "BufNewFile",
   },
   cmd = {
      "TSBufDisable",
      "TSBufEnable",
      "TSBufToggle",
      "TSDisable",
      "TSEnable",
      "TSToggle",
      "TSInstall",
      "TSInstallInfo",
      "TSInstallSync",
      "TSModuleInfo",
      "TSUninstall",
      "TSUpdate",
      "TSUpdateSync",
   },
   config = function()
      require("nvim-treesitter.configs").setup({
         ensure_installed = {
            "bash",
            "c",
            "cmake",
            "css",
            "diff",
            "go",
            "html",
            "javascript",
            "json",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "printf",
            "python",
            "query",
            "regex",
            "rust",
            "sql",
            "svelte",
            "toml",
            "tsx",
            "typescript",
            "vala",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
            "zig",
         },
         sync_install = false,
         auto_install = true,
         ignore_install = {},
         highlight = {
            enable = true,
         },
      })
   end,
}

